### ISSUE TITLE
BROKEN

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/BeautifulComments#10]
In the process of removing bloat from MicRichTextComposer I removed a few methods which was used only by BeautifulComments, breaking BeautifulComments.

It is a rather simple fix, and it will be fixed in the BeautifulComments project to make the seperation between the two cleaner.

**Comment by Ducasse** [comment]
Thanks for taking care.

**Comment by kasperosterbye** [comment]
This fixed BeautifulComments depends on [Microdown PR 291](https://github.com/pillar-markup/Microdown/pull/291) being done first.

But except for that - it is ready to roll.

**Comment by kasperosterbye** [comment]
fixed by PR #11
