### ISSUE TITLE
Class comment of ClyEditCommentSwitchMorph can be clearified

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/BeautifulComments#5]
In particular clarify that it is the toggle in the lower left corner, and that it can be activated by the keyboard shortcut defined in  `ClyRichTextClassCommentEditorToolMorph>>buildTextMorph` - command-r

**Comment by Ducasse** [comment]
Yes. Now I got burnt by calypso and I do not have always the correct behavior with command-r

**Comment by kasperosterbye** [comment]
It is this button I am talking about:
![image](https://user-images.githubusercontent.com/17723745/138033110-0e1d1cf6-cef0-4c20-8bdd-7bdd1572beb2.png)
(new trick - by adding images to issues, they get a url which can be used in microdown)

**Comment by kasperosterbye** [comment]
Fixed by PR #7
