### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/BeautifulComments#9]
There is a settings part in `MicRichTextComposer>>preferencesSettingsOn:`. 
Reading the comments of what the various settings does, I believe they make more sense in the BeautifulComments project. For example one can choose not to render in the MicRichTextComposer - which make make no sense to me.

**Comment by Ducasse** [comment]
Yes this is probably a leftover of the split into beautiful comments.

**Comment by kasperosterbye** [comment]
Fixed by #11
